version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null

  superhero:
    build: .
    container_name: superhero
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    depends_on:
      - mongo
