spring:
  application.name: payworks-superhero
  profiles.active: dev

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_empty
    serialization.write-dates-as-timestamps: false

  data:
    mongodb:
      repositories:
        type: reactive

logging:
  file: application.log

---

spring:
  profiles: dev

---

spring:
  profiles: prod

  data:
    mongodb:
      uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}?retryWrites=true

  security:
    user:
      name: ${USR_NAME}
      password: ${USR_PASSWORD}
