spring:
  application.name: payworks-superhero
  profiles.active: dev

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_empty
    serialization.write-dates-as-timestamps: false

logging:
  file: application.log

---

spring:
  profiles: dev

  data:
    mongodb:
      database: superhero
      host: localhost
      port: 27017
      repositories:
        type: reactive

---

spring:
  profiles: prod

  data:
    mongodb:
      repositories:
        type: reactive
      uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}?retryWrites=true
  security:
    user:
      name: ${USR_NAME}
      password: ${USR_PASSWORD}
